version: '3'
services:
  service:
    build: app
    container_name: service
    volumes:
      - static:/opt/app/static
    depends_on:
      - postgres
    expose:
      - "8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/
    depends_on:
      - service
    ports:
      - "80:80"

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  static: